import feedparser
import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry
import urllib3
import re
import concurrent.futures
from datetime import datetime
import time

# 🚨 SSL 경고 제거 (필수)
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# ---------------------------------------------------------
# 1. 2026년 기준 검증된 '살아있는' 보안 뉴스 채널 (35개+)
# ---------------------------------------------------------
RSS_FEEDS = {
    "🇰🇷 국내 핵심 (Verified)": [
        {"title": "보안뉴스 (BoanNews)", "url": "https://www.boannews.com/media/news_rss.xml"},
        {"title": "데일리시큐 (DailySecu)", "url": "https://www.dailysecu.com/rss/allArticle.xml"},
        {"title": "전자신문 (Security)", "url": "https://rss.etnews.com/04045.xml"},
        {"title": "바이라인네트워크 (IT/Security)", "url": "https://byline.network/feed/"}, # ZDNet 대체
        {"title": "ITWorld (Security)", "url": "https://www.itworld.co.kr/rss/topics/security"},
    ],
    "🛡️ 글로벌 위협 인텔리전스 (Top Tier)": [
        {"title": "Palo Alto Unit 42", "url": "https://unit42.paloaltonetworks.com/feed/"}, # AhnLab 대체
        {"title": "Mandiant Threat Research", "url": "https://www.mandiant.com/resources/blog/rss.xml"},
        {"title": "Recorded Future", "url": "https://www.recordedfuture.com/feed"},
        {"title": "SentinelOne", "url": "https://www.sentinelone.com/feed/"},
    ],
    "🌍 글로벌 뉴스 (Must Read)": [
        {"title": "The Hacker News", "url": "https://feeds.feedburner.com/TheHackersNews"},
        {"title": "BleepingComputer", "url": "https://www.bleepingcomputer.com/feed/"},
        {"title": "SecurityWeek", "url": "https://feeds.feedburner.com/SecurityWeek"}, # PacketStorm 대체
        {"title": "Help Net Security", "url": "https://www.helpnetsecurity.com/feed/"},
        {"title": "The CyberWire", "url": "https://thecyberwire.com/feeds/rss.xml"},
    ],
    "🏢 빅테크 & 클라우드 보안": [
        {"title": "Microsoft Security", "url": "https://www.microsoft.com/security/blog/feed/"},
        {"title": "Google Online Security", "url": "https://security.googleblog.com/feeds/posts/default"},
        {"title": "AWS Security", "url": "https://aws.amazon.com/blogs/security/feed/"},
        {"title": "Cloudflare", "url": "https://blog.cloudflare.com/rss/"},
    ],
    "🐛 취약점 & 심층 분석": [
        {"title": "Exploit-DB", "url": "https://www.exploit-db.com/rss.xml"},
        {"title": "Schneier on Security", "url": "https://www.schneier.com/feed/atom/"},
        {"title": "Trend Micro Research", "url": "https://feeds.feedburner.com/TrendMicroResearch"},
        {"title": "Qualys Security", "url": "https://blog.qualys.com/feed"},
    ]
}

# ---------------------------------------------------------
# 2. 봇 차단 우회 및 연결 설정
# ---------------------------------------------------------
def create_session():
    session = requests.Session()
    # 리얼 크롬 브라우저 헤더 (User-Agent)
    session.headers.update({
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
        'Referer': 'https://www.google.com/'
    })
    # 재시도 로직 (Timeout 방지)
    retry = Retry(total=2, backoff_factor=1, status_forcelist=[500, 502, 503, 504])
    adapter = HTTPAdapter(max_retries=retry)
    session.mount("https://", adapter)
    session.mount("http://", adapter)
    return session

def clean_html(raw_html):
    if not raw_html: return ""
    text = re.sub(r'<[^>]+>', '', raw_html).strip() # 태그 제거
    return text[:150] + "..." if len(text) > 150 else text

def fetch_single_feed(feed):
    session = create_session()
    try:
        # verify=False로 인증서 에러 패스, timeout=15초
        resp = session.get(feed['url'], timeout=15, verify=False)
        
        # 404 체크
        if resp.status_code == 404:
            return [], f"⚠️ 주소 404 (삭제됨): {feed['title']}"
            
        resp.raise_for_status()
        
        # 파싱 시도 (content -> text 순서로 시도)
        parsed = feedparser.parse(resp.content)
        if not parsed.entries:
            parsed = feedparser.parse(resp.text)
            
        if not parsed.entries:
            return [], f"⚠️ 데이터 없음 (빈 피드): {feed['title']}"
            
        return parsed.entries[:5], feed['title']

    except Exception as e:
        return [], f"❌ 접속 실패 ({feed['title']}): {str(e)[:30]}"

# ---------------------------------------------------------
# 3. 메인 실행 (수정된 카운팅 로직)
# ---------------------------------------------------------
def main():
    start = time.time()
    today = datetime.now().strftime("%Y-%m-%d")
    
    md_output = f"# 🛡️ Security News Briefing ({today})\n"
    md_output += f"> 🤖 Auto-generated by GitHub Actions | {datetime.now().strftime('%H:%M KST')}\n\n"
    
    total_articles = 0 # 전체 기사 수 카운터
    
    for category, feeds in RSS_FEEDS.items():
        md_output += f"## {category}\n"
        print(f"\n📂 {category}")
        
        # 병렬 수집 시작
        with concurrent.futures.ThreadPoolExecutor(max_workers=20) as executor:
            future_to_feed = {executor.submit(fetch_single_feed, feed): feed for feed in feeds}
            
            # 카테고리별 결과 임시 저장
            category_results = []
            
            for future in concurrent.futures.as_completed(future_to_feed):
                entries, msg_or_title = future.result()
                
                if entries: # 기사가 있으면 성공
                    category_results.append((msg_or_title, entries))
                    print(f"  ✅ Fetched: {msg_or_title} ({len(entries)} articles)")
                else: # 기사가 없으면 실패 메시지 출력
                    print(f"  {msg_or_title}")

            # 리포트 작성 (결과가 있을 때만)
            if not category_results:
                md_output += "> *No updates available.*\n\n"
                continue
                
            # 정렬 후 출력
            category_results.sort(key=lambda x: x[0])
            
            for title, entries in category_results:
                md_output += f"<details><summary><b>{title}</b></summary>\n\n"
                for entry in entries:
                    link = entry.link
                    summary = clean_html(getattr(entry, 'summary', getattr(entry, 'description', '')))
                    # 날짜 (없으면 생략)
                    published = getattr(entry, 'published', '')[:16]
                    
                    md_output += f"- **[{entry.title}]({link})**\n"
                    if published:
                        md_output += f"  - <small>📅 {published}</small>\n"
                    md_output += f"  - {summary}\n\n"
                    
                    total_articles += 1 # 카운터 증가
                md_output += "</details>\n"
        
        md_output += "---\n"

    elapsed = time.time() - start
    print(f"\n✨ DONE! Total {total_articles} articles collected in {elapsed:.2f}s")
    
    # 결과 파일 저장
    with open("daily_security_report.md", "w", encoding="utf-8") as f:
        f.write(md_output)

if __name__ == "__main__":
    main()
