import os
import json

# ==============================================================================
# 🏗️ [설정] 프로젝트 경로
# ==============================================================================
BASE_DIR = os.getcwd()
PROJECT_NAME = "services/omni-pokemon-web" # (폴더명 유지)
PROJECT_ROOT = os.path.join(BASE_DIR, PROJECT_NAME)

SRC_MAIN = os.path.join(PROJECT_ROOT, "src/main")
JAVA_PKG = os.path.join(SRC_MAIN, "java/com/omni/ai")
RESOURCES = os.path.join(SRC_MAIN, "resources")
STATIC_DIR = os.path.join(RESOURCES, "static")
WORKFLOWS_DIR = os.path.join(BASE_DIR, ".github/workflows")

def write_file(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content.strip())
    print(f"✅ [생성] {os.path.basename(path)}")

# ==============================================================================
# 1. 🐍 CI 내부용 리소스 생성 스크립트 (setup_resources.py)
# ==============================================================================
def generate_python_setup_script():
    # 이 스크립트는 CI 서버(GitHub Actions)에서 'Run Setup' 단계에 실행됩니다.
    script_content = """
import os
import json

def main():
    print("🚀 [CI] Generating AI Data Resources...")
    
    # 2026 AI Trends Data
    data = {
        "meta": {"version": "2026.8.0", "desc": "Generated by CI Pipeline"},
        "rankings": [
            {"rank": 1, "name": "Gemini-3-Pro", "score": 1492, "desc": "Universal King (Google)"},
            {"rank": 2, "name": "Grok-4.1", "score": 1482, "desc": "Reasoning Monster (xAI)"},
            {"rank": 3, "name": "Claude-Opus-4.5", "score": 1466, "desc": "Coding Architect (Anthropic)"}
        ],
        "features": [
            {"title": "PWA Ready", "val": "Yes"},
            {"title": "Smart CI", "val": "Active"}
        ]
    }
    
    # Ensure directory
    res_dir = "services/omni-pokemon-web/src/main/resources"
    os.makedirs(res_dir, exist_ok=True)
    
    # Write JSON
    with open(os.path.join(res_dir, "ai_data.json"), "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)
        
    print(f"✅ Data generated at: {res_dir}/ai_data.json")

if __name__ == "__main__":
    main()
"""
    write_file(os.path.join(BASE_DIR, "setup_resources.py"), script_content)

# ==============================================================================
# 2. 🤖 GitHub Actions (사용자 요청 반영 + 기능 강화)
# ==============================================================================
def generate_workflow():
    write_file(os.path.join(WORKFLOWS_DIR, "ultimate_ci.yml"), """
name: Ultimate CI/CD (Resource & AI Fix)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Python 환경 (리소스 생성용)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      # 2. Java 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # 3. [핵심] 리소스 동적 생성 (JSON 파일 분리 저장)
      - name: 🚀 Run Setup (Externalize Data)
        run: |
          if [ -f setup_resources.py ]; then
            echo "⚡ setup_resources.py 실행: AI 데이터 생성 중..."
            python setup_resources.py
          else
            echo "❌ 설정 스크립트가 없습니다."
            exit 1
          fi

      # 4. 빌드 (생성된 리소스 포함)
      - name: Build with Maven
        working-directory: services/omni-pokemon-web
        run: mvn clean package -DskipTests -B

      # 5. 서버 테스트 (Smart Polling + AI Data 검증)
      - name: 🌐 Server Smoke Test (Smart Mode)
        working-directory: services/omni-pokemon-web
        run: |
          echo "🔥 서버 시작 (JVM 옵션 최적화)..."
          # 한글 인코딩 및 메모리 설정
          nohup java -Xmx512m -Dfile.encoding=UTF-8 -jar target/*.jar > app.log 2>&1 &
          PID=$!
          
          echo "⏳ 부팅 대기 (Smart Polling: Max 60s)..."
          # 기존 sleep 20 -> Smart Loop로 변경
          BOOTED=false
          for i in {1..30}; do
            sleep 2
            HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8086/api/system/health || echo "000")
            if [ "$HTTP_CODE" -eq 200 ]; then
              echo "✅ 서버 가동 확인 (Attempt $i)"
              BOOTED=true
              break
            fi
            echo "   Wait... $i"
          done

          if [ "$BOOTED" = "false" ]; then
             echo "❌ 부팅 타임아웃!"
             cat app.log
             kill $PID
             exit 1
          fi

          echo "🧪 1. Health Check: OK"
          
          echo "🧪 2. 대량 데이터 검색 (Gemini/Claude 확인)"
          # URL 인코딩 테스트
          SEARCH_RES=$(curl -s -G --data-urlencode "keyword=Gemini" http://localhost:8086/api/ai/trends)
          
          echo "Search Result Length: ${#SEARCH_RES}"
          
          # Gemini가 포함되어야 성공
          if [[ "$SEARCH_RES" == *"Gemini"* ]]; then
            echo "✅ 테스트 성공! (AI 데이터 로드 및 인코딩 정상)"
            kill $PID
            exit 0
          else
            echo "❌ 데이터 검증 실패"
            echo "응답: $SEARCH_RES"
            cat app.log
            kill $PID
            exit 1
          fi

      # 6. 아티팩트 업로드
      - name: 📤 Upload Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: server-logs-and-jar
          path: |
            services/omni-pokemon-web/app.log
            services/omni-pokemon-web/target/*.jar
""")

# ==============================================================================
# 3. ☕ Java Backend (AI Trends 2026)
# ==============================================================================
def generate_backend():
    # 1. Model
    write_file(os.path.join(JAVA_PKG, "model/AiData.java"), """
package com.omni.ai.model;
import lombok.Data;
import java.util.List;
import java.util.Map;

@Data
public class AiData {
    private Map<String, String> meta;
    private List<Ranking> rankings;
    private List<Feature> features;
    
    @Data public static class Ranking { int rank; String name; int score; String desc; }
    @Data public static class Feature { String title; String val; }
}
""")

    # 2. Service (Load JSON)
    write_file(os.path.join(JAVA_PKG, "service/AiService.java"), """
package com.omni.ai.service;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.omni.ai.model.AiData;
import org.springframework.stereotype.Service;
import jakarta.annotation.PostConstruct;
import java.io.InputStream;

@Service
public class AiService {
    private AiData data;
    private final ObjectMapper mapper = new ObjectMapper();

    @PostConstruct
    public void init() {
        try (InputStream is = getClass().getResourceAsStream("/ai_data.json")) {
            if (is != null) data = mapper.readValue(is, AiData.class);
            else System.err.println("❌ ai_data.json not found!");
        } catch (Exception e) { e.printStackTrace(); }
    }
    public AiData getData() { return data; }
}
""")

    # 3. Controller
    write_file(os.path.join(JAVA_PKG, "controller/AiController.java"), """
package com.omni.ai.controller;
import com.omni.ai.service.AiService;
import com.omni.ai.model.AiData;
import org.springframework.web.bind.annotation.*;
import lombok.RequiredArgsConstructor;

@RestController
@RequestMapping("/api")
@RequiredArgsConstructor
public class AiController {
    private final AiService service;

    @GetMapping("/ai/trends")
    public AiData getTrends(@RequestParam(required=false) String keyword) { 
        // 키워드 검색 로직 (Mock)
        return service.getData(); 
    }
    
    @GetMapping("/system/health")
    public String health() { return "OK"; }
}
""")

    # 4. Main App
    write_file(os.path.join(JAVA_PKG, "OmniAiApp.java"), """
package com.omni.ai;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
@SpringBootApplication
public class OmniAiApp {
    public static void main(String[] args) { SpringApplication.run(OmniAiApp.class, args); }
}
""")

    # 5. POM (Maven Fix)
    write_file(os.path.join(PROJECT_ROOT, "pom.xml"), """
<project xmlns="http://maven.apache.org/POM/4.0.0" 
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.omni</groupId>
    <artifactId>omni-pokemon-web</artifactId>
    <version>2026.8.0-ULTIMATE</version>
    <packaging>jar</packaging>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.1</version>
        <relativePath/> 
    </parent>

    <properties>
        <java.version>17</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-web</artifactId></dependency>
        <dependency><groupId>org.projectlombok</groupId><artifactId>lombok</artifactId><optional>true</optional></dependency>
        <dependency><groupId>com.fasterxml.jackson.core</groupId><artifactId>jackson-databind</artifactId></dependency>
    </dependencies>
    <build><plugins><plugin><groupId>org.springframework.boot</groupId><artifactId>spring-boot-maven-plugin</artifactId></plugin></plugins></build>
</project>
""")

    # 6. Properties
    write_file(os.path.join(RESOURCES, "application.properties"), "server.port=8086")

# ==============================================================================
# 4. 🎨 Frontend (PWA + Neon UI)
# ==============================================================================
def generate_frontend():
    # PWA Manifest
    write_file(os.path.join(STATIC_DIR, "manifest.json"), json.dumps({
        "name": "2026 AI Trends",
        "short_name": "AI 2026",
        "start_url": "/",
        "display": "standalone",
        "theme_color": "#0f172a",
        "background_color": "#0f172a",
        "icons": [{"src": "https://cdn-icons-png.flaticon.com/512/2040/2040946.png", "sizes": "512x512", "type": "image/png"}]
    }, indent=2))

    # Service Worker
    write_file(os.path.join(STATIC_DIR, "sw.js"), """
self.addEventListener('install', e => e.waitUntil(caches.open('ai-v8').then(c => c.addAll(['/', '/index.html']))));
self.addEventListener('fetch', e => e.respondWith(caches.match(e.request).then(r => r || fetch(e.request))));
""")

    # HTML
    write_file(os.path.join(STATIC_DIR, "index.html"), """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI 2026 Insight</title>
    <link rel="manifest" href="/manifest.json">
    <script src="https://cdn.tailwindcss.com"></script>
    <script>if('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js');</script>
</head>
<body class="bg-slate-900 text-white p-6">
    <h1 class="text-3xl font-bold mb-6 text-blue-400">2026 AI Trends (CI Verified)</h1>
    <div id="list" class="space-y-4">Loading...</div>
    <script>
        fetch('/api/ai/trends').then(r => r.json()).then(d => {
            document.getElementById('list').innerHTML = d.rankings.map(r => `
                <div class="bg-slate-800 p-4 rounded-xl border border-slate-700">
                    <span class="text-yellow-400 font-bold">#${r.rank}</span> 
                    <span class="font-bold text-lg ml-2">${r.name}</span>
                    <div class="text-sm text-slate-400">${r.desc}</div>
                </div>
            `).join('');
        });
    </script>
</body>
</html>
""")

# ==============================================================================
# 5. 🚀 Push Script
# ==============================================================================
def generate_push_script():
    script_path = os.path.join(BASE_DIR, "push_v8.sh")
    write_file(script_path, """
#!/bin/bash
echo "🚀 Deploying V8: Resource Setup + PWA + Smart CI..."
git config --global user.email "bot@omni.com"
git config --global user.name "Omni Bot"

# 리소스 생성 스크립트도 함께 푸시해야 CI에서 실행됨
git add setup_resources.py
git add .
git commit -m "Feat: Complete Update - Resource Generator script and Smart Polling CI"
git push
echo "✅ Done."
""")
    if os.name != 'nt': os.chmod(script_path, 0o755)

# ==============================================================================
# Main
# ==============================================================================
if __name__ == "__main__":
    print("🤖 Generating Ultimate Platform V8...")
    generate_python_setup_script() # CI에서 사용할 Python 스크립트 생성
    generate_workflow()            # 개선된 CI YAML
    generate_backend()             # Java
    generate_frontend()            # HTML + PWA
    generate_push_script()
    
    print("\n✅ V8 생성 완료.")
    print("👉 './push_v8.sh' 를 실행하여 GitHub에 반영하세요.")
