version: '3.8'
services:
  soc-server:
    image: nginx:alpine
    container_name: omni-soc
    ports:
      - "8080:80"
    volumes:
      - ../:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
