apiVersion: apps/v1
kind: Deployment
metadata:
  name: omni-algo
  labels:
    app: omni-algo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: omni-algo
  template:
    metadata:
      labels:
        app: omni-algo
    spec:
      containers:
      - name: app
        image: ghcr.io/koreatest12/cost-data/omni-algo-service:latest
        ports:
        - containerPort: 8080
